</div>
<div class="mx-auto" style="width:90%;margin-top:5%;text-align:center">
    <hr>
    <p style="color: gray; font-family: 'Roboto Mono'"><span style="display: inline-block">Made by <a
                style="color:black" href="https://twitter.com/yudete">yude</a>.</span> | <a href="about"><span
                style="display: inline-block;color:black">
                <span data-i18n="index.about"></span>
            </span></a></p>
</div>
</div>
</div>
</body>

</html>