<!doctype html>
<html lang="ja">

<head>
    <title>{{ title }} ・ yude.moe</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="dns-prefetch" href="//stackpath.bootstrapcdn.com">
    <link rel="dns-prefetch" href="//code.jquery.com">
    <link rel="dns-prefetch" href="//cdnjs.cloudflare.com">
    <link rel="icon" href="assets/favicon.ico">

    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP|Roboto+Mono&display=swap" rel="stylesheet"
        media="print" onload="this.media='all'" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/fontawesome.min.css"
        integrity="sha256-0mlw4Ae1j9eDzZTzLuw5X9fBCL9nAehrtVyKfIstZQA=" crossorigin="anonymous" media="print"
        onload="this.media='all'" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha256-L/W5Wfqfa0sdBNIKN9cG6QA5F2qx4qICmU2VgLruv9Y=" crossorigin="anonymous" media="print"
        onload="this.media='all'" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css"
        integrity="sha256-PHcOkPmOshsMBC+vtJdVr5Mwb7r0LkSVJPlPrp/IMpU=" crossorigin="anonymous" media="print"
        onload="this.media='all'" />
    <meta property="og:url" content="https://yude.moe" />
    <meta property="og:image" content="https://yude.moe/assets/mel-full.jpg" />
    <meta property="og:description" content="{{ title }}" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@yudemoe" />
    <style>
        .fa-svg svg {
            height: 9rem;
            max-width: 9.5rem;
        }

        .fa-svg path {
            fill: #fff;
        }

        @font-face {
            font-family: 'Font Awesome 5 Brands';
            font-style: normal;
            font-weight: 400;
            src: url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/webfonts/fa-brands-400.woff2") format("woff2");
            font-display: swap;
        }

        @font-face {
            font-family: 'Font Awesome 5 Free';
            font-style: normal;
            font-weight: 900;
            src: url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/webfonts/fa-solid-900.woff2") format("woff2");
            font-display: swap;
        }

        @font-face {
            font-family: 'Morning Star';
            src: local('Morning Star'),
                url('../assets/fonts/MorningStar.ttf');
        }

        body {
            font-family: 'Font Awesome 5 Brands', 'Font Awesome 5 Free', 'Roboto Mono', "Noto Sans JP";
            background-color: #262a2f;
        }

        canvas {
            display: block;
        }


        .text {
            position: absolute;
            right: 5px;
            bottom: 10px;
            font-size: 20px;
            line-height: 130%;
        }

        .bg {
            background-image: url("../assets/marisa_2x.webp");
            background-repeat: no-repeat;
        }

        .fa-svg svg {
            height: 18px;
            max-width: 20px;

        }

        .fa-svg path {
            fill: #262a2f;
        }

        a:link {
            color: #778899;
        }

        a:visited {
            color: #778899;
        }

        a:hover {
            color: #778899;
        }

        a:active {
            color: #778899;
        }

        code {
            font-size: 20px;
        }

        .box {
            width: 100px;
            margin: 0;
            display: inline-block;
        }

        button.dayo {
            background-color: #0F96AA;
            color: #E1E1E1;
        }

        .hvr-bounce-in {
            color: #CAB1FF
        }
    </style>
</head>

<body>